name: flutter_ijkplayer
description: Base by bilibili ijkplayer, it's video/audio player, support https、rtmp、m3u8 and more protocol.
version: 0.3.1
author: caijinglong<cjl_spy@163.com>
homepage: https://github.com/CaiJingLong/flutter_ijkplayer

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  plugin:
    androidPackage: top.kikt.ijkplayer
    pluginClass: IjkplayerPlugin
